<a href="https://colab.research.google.com/github/see-3pO/Learning_Tensorflow/blob/master/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import  tensorflow as tf

## Initialization of Tensors

In [ ]:
x = tf.constant(2, shape=(1,1), dtype=tf.float32)
x = tf.constant([[1, 2, 3], [3, 4, 5]])
print(x)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [ ]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.zeros((2, 2))
print(x)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [ ]:
# Identity matrix
x = tf.eye(4, dtype=tf.int32)
print(x)

tf.Tensor(
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]], shape=(4, 4), dtype=int32)


In [ ]:
# standard normal distribution
x = tf.random.normal(shape=(3, 3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.24003953 -0.78013355 -0.73335826]
 [-0.5353748   1.0091451   0.5240714 ]
 [ 0.70982355 -0.24213453 -0.373464  ]], shape=(3, 3), dtype=float32)


In [ ]:
# Uniform distribution
x = tf.random.uniform(shape=(3, 3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.1808691  0.03093362 0.51099384]
 [0.10335732 0.9898552  0.28080845]
 [0.4312998  0.53219295 0.3244841 ]], shape=(3, 3), dtype=float32)


In [ ]:
# range
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
# convert to specific type
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


## Mathematical Operations

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

In [ ]:
# addition
z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
# subtraction
z = tf.subtract(x, y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [ ]:
# multiplication
z = tf.multiply(x, y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [ ]:
# division
z = tf.divide(x, y)
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [ ]:
# dot product
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [ ]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [ ]:
# elementwise exponentiation
z =  x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [ ]:
# matrix multiplication
a = tf.random.normal((2, 3))
b = tf.random.normal((3, 4))
c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[-1.0205872   1.3323843   0.30514318  1.3564851 ]
 [-0.60767263  3.0973375   0.4838372   1.8268143 ]], shape=(2, 4), dtype=float32)


In [ ]:
# matrix multiplication
c = a @ b
print(c)

tf.Tensor(
[[-1.0205872   1.3323843   0.30514318  1.3564851 ]
 [-0.60767263  3.0973375   0.4838372   1.8268143 ]], shape=(2, 4), dtype=float32)


## Indexing of a tensor

In [ ]:
x = tf.constant([1, 2, 3, 4, 5, 6])
print(x)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
print(x[1:])

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


In [ ]:
print(x[:4])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
# skipping the elements using step value of 2
print(x[::2])

tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [ ]:
# skipping the elements using step value of 3
print(x[::3])

tf.Tensor([1 4], shape=(2,), dtype=int32)


In [ ]:
# reverse order
print(x[::-1])

tf.Tensor([6 5 4 3 2 1], shape=(6,), dtype=int32)


In [ ]:
indices = tf.constant([0, 4])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([1 5], shape=(2,), dtype=int32)


In [ ]:
x = tf.constant([[3, 4, 5],
                [7, 8, 9],
                [1, 2, 0]])
print(x)

tf.Tensor(
[[3 4 5]
 [7 8 9]
 [1 2 0]], shape=(3, 3), dtype=int32)


In [ ]:
# indexing matrix fir first row
print(x[0])

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [ ]:
# alternative method
# select first row then select all columns in that row
print(x[0, :])

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [ ]:
# select first two rows and all the columns belonging to those rows
print(x[0:2, :])

tf.Tensor(
[[3 4 5]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [ ]:
print(x[1:, :])

tf.Tensor(
[[7 8 9]
 [1 2 0]], shape=(2, 3), dtype=int32)


## Reshaping

In [ ]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [ ]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [ ]:
# transpose
x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
